# -*- coding: utf-8 -*-
"""Frontend3.pynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EKu5SjLDavmyf1MhNgOfUZgCpjFgOKBI
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import hashlib
import sqlite3
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from PIL import Image
import urllib.request
import time
from datetime import datetime
import requests
import warnings
import json
import os
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from wordcloud import WordCloud
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
from datetime import timedelta
import re

# Suppress warnings
warnings.filterwarnings("ignore")

# ====================== CONFIGURATION ======================
# Environment variables for sensitive data
RAPIDAPI_KEY = os.getenv('RAPIDAPI_KEY', 'ec70c1e9bbmsh1a7dca9ef97a387p19ee42jsnbe4f065214d1')
NEWSAPI_KEY = os.getenv('NEWSAPI_KEY', '98093fbf8bcd4a37a7035b52273c50bf')
LINKEDIN_CLIENT_ID = os.getenv('LINKEDIN_CLIENT_ID', '')
LINKEDIN_CLIENT_SECRET = os.getenv('LINKEDIN_CLIENT_SECRET', '')

# Email configuration
EMAIL_CONFIG = {
    'sender': os.getenv('EMAIL_SENDER', 'mehirsaxena34@gmail.com'),
    'password': os.getenv('EMAIL_PASSWORD', 'rtmd wkzq enat kxyt'),
    'smtp_server': os.getenv('SMTP_SERVER', 'smtp.gmail.com'),
    'smtp_port': int(os.getenv('SMTP_PORT', 587))
}

# ====================== ENHANCED BACKEND CLASSES ======================
class EnhancedJobFinder:
    def __init__(self, file_path="Job opportunities1.csv"):
        """Load job dataset with enhanced processing"""
        try:
            self.df = pd.read_csv(file_path, encoding="ISO-8859-1")
            # Enhanced data cleaning
            self.df['Required Skills'] = self.df['Required Skills'].fillna('').apply(lambda x: x.lower())
            self.df['Location'] = self.df['Location'].fillna('Remote').apply(lambda x: x.title())
            self.df['Company'] = self.df['Company'].fillna('').apply(lambda x: x.title())

            # Extract salary information if available
            if 'Salary Range' in self.df.columns:
                self.df['Min Salary'] = self.df['Salary Range'].apply(self._extract_min_salary)
                self.df['Max Salary'] = self.df['Salary Range'].apply(self._extract_max_salary)

            # Create skill vectors for recommendation
            self._create_skill_vectors()

        except Exception as e:
            st.error(f"Error loading job data: {str(e)}")
            self.df = pd.DataFrame()

    def _extract_min_salary(self, salary_str):
        """Extract minimum salary from salary range string"""
        if pd.isna(salary_str):
            return None
        numbers = re.findall(r'\d+', str(salary_str))
        if numbers:
            return int(numbers[0])
        return None

    def _extract_max_salary(self, salary_str):
        """Extract maximum salary from salary range string"""
        if pd.isna(salary_str):
            return None
        numbers = re.findall(r'\d+', str(salary_str))
        if len(numbers) > 1:
            return int(numbers[1])
        return None

    def _create_skill_vectors(self):
        """Create TF-IDF vectors for skill-based recommendations"""
        if self.df.empty:
            return

        # Create a TF-IDF vectorizer
        self.vectorizer = TfidfVectorizer(stop_words='english', max_features=1000)
        skill_texts = self.df['Required Skills'].fillna('')
        self.skill_vectors = self.vectorizer.fit_transform(skill_texts)

    def filter_jobs(self, Required_Skill="", location="", experience="", company=""):
        """Enhanced job filtering with more parameters"""
        if self.df.empty:
            return None

        filtered_df = self.df.copy()

        if Required_Skill:
            filtered_df = filtered_df[filtered_df['Required Skills'].str.contains(Required_Skill.lower(), case=False, na=False)]
        if location:
            filtered_df = filtered_df[filtered_df['Location'].str.contains(location, case=False, na=False)]
        if company:
            filtered_df = filtered_df[filtered_df['Company'].str.contains(company, case=False, na=False)]

        experience_levels = {
            "entry": ["Entry Level", "0-1 Years", "Intern"],
            "junior": ["Junior", "1-2 Years", "1-3 Years"],
            "mid": ["Mid-Level", "3-5 Years", "2-4 Years", "3-4 Years"],
            "senior": ["Senior", "5-10 Years", "4-6 Years", "5-7 Years"],
            "executive": ["Executive", "Director", "10+ Years", "7+ Years"]
        }

        if experience.lower() in experience_levels:
            exp_categories = experience_levels[experience.lower()]
            filtered_df = filtered_df[filtered_df['Experience Level'].str.contains('|'.join(exp_categories), case=False, na=False)]

        return filtered_df if not filtered_df.empty else None

    def recommend_jobs(self, user_skills, top_n=5):
        """Recommend jobs based on user skills using cosine similarity"""
        if self.df.empty or not hasattr(self, 'vectorizer'):
            return None

        # Transform user skills to vector
        user_skills_text = ' '.join(user_skills).lower()
        user_vector = self.vectorizer.transform([user_skills_text])

        # Calculate similarity
        similarities = cosine_similarity(user_vector, self.skill_vectors).flatten()

        # Get top N recommendations
        top_indices = similarities.argsort()[-top_n:][::-1]
        recommended_jobs = self.df.iloc[top_indices].copy()
        recommended_jobs['Match Score'] = similarities[top_indices]

        return recommended_jobs

    def get_skill_demand(self):
        if self.df.empty:
            return pd.Series()
        return self.df['Required Skills'].str.split(', ').explode().value_counts().head(15)

    def get_location_distribution(self):
        if self.df.empty:
            return pd.Series()
        return self.df['Location'].value_counts().head(10)

    def get_salary_analysis(self):
        if self.df.empty or 'Min Salary' not in self.df.columns:
            return pd.DataFrame()

        salary_df = self.df[['Experience Level', 'Min Salary', 'Max Salary']].dropna()
        if salary_df.empty:
            return pd.DataFrame()

        # Calculate average salary by experience level
        salary_stats = salary_df.groupby('Experience Level').agg({
            'Min Salary': 'mean',
            'Max Salary': 'mean'
        }).round(0)

        return salary_stats

    def get_company_insights(self):
        if self.df.empty:
            return pd.DataFrame()

        company_stats = self.df['Company'].value_counts().head(10)
        return company_stats

class RealTimeJobFetcher:
    def __init__(self, api_key):
        self.api_key = api_key

    def fetch_jobs(self, skill, location="", page=1, num_pages=1):
        try:
            url = "https://jsearch.p.rapidapi.com/search"
            query = f"{skill} developer"
            if location:
                query += f" in {location}"

            querystring = {
                "query": query,
                "page": str(page),
                "num_pages": str(num_pages),
                "date_posted": "month",
                "employment_types": "FULLTIME,PARTTIME,CONTRACTOR"
            }

            headers = {
                "X-RapidAPI-Key": self.api_key,
                "X-RapidAPI-Host": "jsearch.p.rapidapi.com"
            }

            response = requests.get(url, headers=headers, params=querystring, timeout=10)
            response.raise_for_status()

            data = response.json()
            return data.get("data", [])

        except requests.exceptions.RequestException as e:
            st.error(f"Error fetching jobs: {str(e)}")
            return []
        except Exception as e:
            st.error(f"Unexpected error: {str(e)}")
            return []

class LinkedInIntegration:
    def __init__(self, client_id, client_secret):
        self.client_id = client_id
        self.client_secret = client_secret
        self.redirect_uri = "http://localhost:8000/callback"  # Update with your redirect URI

    def get_auth_url(self):
        """Generate LinkedIn OAuth2 authorization URL"""
        auth_url = f"https://www.linkedin.com/oauth/v2/authorization?response_type=code&client_id={self.client_id}&redirect_uri={self.redirect_uri}&scope=r_liteprofile%20r_emailaddress%20w_member_social"
        return auth_url

    def get_profile_data(self, access_token):
        """Fetch LinkedIn profile data"""
        try:
            headers = {'Authorization': f'Bearer {access_token}'}
            response = requests.get('https://api.linkedin.com/v2/me', headers=headers)
            response.raise_for_status()
            return response.json()
        except Exception as e:
            st.error(f"Error fetching LinkedIn profile: {str(e)}")
            return None

class LearningResources:
    def __init__(self):
        self.resources = {
            'python': [
                {'name': 'Python for Everybody', 'platform': 'Coursera', 'url': 'https://www.coursera.org/specializations/python'},
                {'name': 'Learn Python 3', 'platform': 'Codecademy', 'url': 'https://www.codecademy.com/learn/learn-python-3'},
                {'name': 'Python Tutorial', 'platform': 'W3Schools', 'url': 'https://www.w3schools.com/python/'}
            ],
            'machine learning': [
                {'name': 'Machine Learning', 'platform': 'Coursera', 'url': 'https://www.coursera.org/learn/machine-learning'},
                {'name': 'Intro to Machine Learning', 'platform': 'Kaggle', 'url': 'https://www.kaggle.com/learn/intro-to-machine-learning'},
                {'name': 'ML Crash Course', 'platform': 'Google', 'url': 'https://developers.google.com/machine-learning/crash-course'}
            ],
            'data analysis': [
                {'name': 'Data Analysis with Python', 'platform': 'freeCodeCamp', 'url': 'https://www.freecodecamp.org/learn/data-analysis-with-python/'},
                {'name': 'Data Analysis', 'platform': 'Kaggle', 'url': 'https://www.kaggle.com/learn/data-analysis'},
                {'name': 'Data Science Fundamentals', 'platform': 'IBM', 'url': 'https://www.coursera.org/professional-certificates/ibm-data-science'}
            ],
            'web development': [
                {'name': 'Web Development', 'platform': 'freeCodeCamp', 'url': 'https://www.freecodecamp.org/learn/responsive-web-design/'},
                {'name': 'Full Stack Open', 'platform': 'University of Helsinki', 'url': 'https://fullstackopen.com/en/'},
                {'name': 'The Odin Project', 'platform': 'Odin', 'url': 'https://www.theodinproject.com/'}
            ]
        }

    def get_resources(self, skill):
        """Get learning resources for a specific skill"""
        skill_lower = skill.lower()
        for key, resources in self.resources.items():
            if key in skill_lower:
                return resources
        return self.resources.get('python', [])  # Default to Python resources

# ====================== INITIALIZATION ======================
job_finder = EnhancedJobFinder()
job_fetcher = RealTimeJobFetcher(RAPIDAPI_KEY)
linkedin_integration = LinkedInIntegration(LINKEDIN_CLIENT_ID, LINKEDIN_CLIENT_SECRET)
learning_resources = LearningResources()

# ====================== ENHANCED DATABASE FUNCTIONS ======================
def get_db_connection():
    """Create and return a database connection"""
    conn = sqlite3.connect('techsphere_enhanced.db', check_same_thread=False)
    conn.row_factory = sqlite3.Row
    return conn

def init_db():
    """Initialize enhanced database tables"""
    conn = get_db_connection()
    try:
        c = conn.cursor()

        # Users table with enhanced fields
        c.execute('''CREATE TABLE IF NOT EXISTS users
                     (username TEXT PRIMARY KEY,
                      password TEXT,
                      email TEXT,
                      skills TEXT,
                      linkedin_profile TEXT,
                      resume_text TEXT,
                      last_notification_check TIMESTAMP,
                      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)''')

        # Saved jobs table
        c.execute('''CREATE TABLE IF NOT EXISTS saved_jobs
                     (id INTEGER PRIMARY KEY AUTOINCREMENT,
                      username TEXT,
                      job_id TEXT,
                      job_details TEXT,
                      source TEXT,
                      applied INTEGER DEFAULT 0,
                      application_date TIMESTAMP,
                      interview_date TIMESTAMP,
                      status TEXT DEFAULT 'Saved',
                      saved_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                      UNIQUE(username, job_id))''')

        # Notifications table
        c.execute('''CREATE TABLE IF NOT EXISTS notifications
                     (id INTEGER PRIMARY KEY AUTOINCREMENT,
                      username TEXT,
                      message TEXT,
                      job_details TEXT,
                      is_read INTEGER DEFAULT 0,
                      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)''')

        # User connections table (networking feature)
        c.execute('''CREATE TABLE IF NOT EXISTS connections
                     (id INTEGER PRIMARY KEY AUTOINCREMENT,
                      user_from TEXT,
                      user_to TEXT,
                      status TEXT DEFAULT 'pending',
                      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                      UNIQUE(user_from, user_to))''')

        # Skill gap analysis table
        c.execute('''CREATE TABLE IF NOT EXISTS skill_gaps
                     (id INTEGER PRIMARY KEY AUTOINCREMENT,
                      username TEXT,
                      missing_skills TEXT,
                      recommended_resources TEXT,
                      analyzed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)''')

        # Interview preparation table
        c.execute('''CREATE TABLE IF NOT EXISTS interview_prep
                     (id INTEGER PRIMARY KEY AUTOINCREMENT,
                      username TEXT,
                      company TEXT,
                      position TEXT,
                      questions TEXT,
                      notes TEXT,
                      prepared_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)''')

        conn.commit()
    except Exception as e:
        st.error(f"Database initialization error: {str(e)}")
    finally:
        conn.close()

init_db()

# ====================== ENHANCED AUTHENTICATION FUNCTIONS ======================
def make_hashes(password):
    """Generate password hash"""
    return hashlib.sha256(str.encode(password)).hexdigest()

def check_hashes(password, hashed_text):
    """Verify password hash"""
    return make_hashes(password) == hashed_text

def create_user(username, password, email, linkedin_profile=""):
    """Create a new user account with enhanced profile"""
    conn = get_db_connection()
    try:
        conn.execute('INSERT INTO users (username, password, email, linkedin_profile) VALUES (?, ?, ?, ?)',
                   (username, make_hashes(password), email, linkedin_profile))
        conn.commit()
        return True
    except sqlite3.IntegrityError:
        return False  # Username already exists
    except Exception as e:
        st.error(f"Error creating user: {str(e)}")
        return False
    finally:
        conn.close()

def login_user(username, password):
    """Authenticate user"""
    conn = get_db_connection()
    try:
        user = conn.execute('SELECT * FROM users WHERE username = ?', (username,)).fetchone()
        if user and check_hashes(password, user['password']):
            return dict(user)
        return None
    except Exception as e:
        st.error(f"Login error: {str(e)}")
        return None
    finally:
        conn.close()

def update_user_profile(username, email=None, skills=None, linkedin_profile=None, resume_text=None):
    """Update user profile information"""
    conn = get_db_connection()
    try:
        if email is not None:
            conn.execute('UPDATE users SET email = ? WHERE username = ?', (email, username))
        if skills is not None:
            conn.execute('UPDATE users SET skills = ? WHERE username = ?', (skills, username))
        if linkedin_profile is not None:
            conn.execute('UPDATE users SET linkedin_profile = ? WHERE username = ?', (linkedin_profile, username))
        if resume_text is not None:
            conn.execute('UPDATE users SET resume_text = ? WHERE username = ?', (resume_text, username))
        conn.commit()
        return True
    except Exception as e:
        st.error(f"Profile update error: {str(e)}")
        return False
    finally:
        conn.close()

# ====================== ENHANCED JOB FUNCTIONS ======================
def save_job(username, job_id, job_details, source):
    """Save a job to user's collection"""
    conn = get_db_connection()
    try:
        conn.execute(
            'INSERT OR IGNORE INTO saved_jobs (username, job_id, job_details, source) VALUES (?, ?, ?, ?)',
            (username, job_id, json.dumps(job_details), source)
        )
        conn.commit()
        return True
    except Exception as e:
        st.error(f"Error saving job: {str(e)}")
        return False
    finally:
        conn.close()

def update_job_status(username, job_id, status, application_date=None, interview_date=None):
    """Update job application status"""
    conn = get_db_connection()
    try:
        if status.lower() == 'applied' and application_date:
            conn.execute(
                'UPDATE saved_jobs SET status = ?, applied = 1, application_date = ? WHERE username = ? AND job_id = ?',
                (status, application_date, username, job_id)
            )
        elif status.lower() == 'interview' and interview_date:
            conn.execute(
                'UPDATE saved_jobs SET status = ?, interview_date = ? WHERE username = ? AND job_id = ?',
                (status, interview_date, username, job_id)
            )
        else:
            conn.execute(
                'UPDATE saved_jobs SET status = ? WHERE username = ? AND job_id = ?',
                (status, username, job_id)
            )
        conn.commit()
        return True
    except Exception as e:
        st.error(f"Error updating job status: {str(e)}")
        return False
    finally:
        conn.close()

def get_saved_jobs(username, status_filter=None):
    """Retrieve user's saved jobs with filtering"""
    conn = get_db_connection()
    try:
        if status_filter:
            jobs = conn.execute(
                'SELECT job_id, job_details, source, status, applied, application_date, interview_date FROM saved_jobs WHERE username = ? AND status = ? ORDER BY saved_at DESC',
                (username, status_filter)
            ).fetchall()
        else:
            jobs = conn.execute(
                'SELECT job_id, job_details, source, status, applied, application_date, interview_date FROM saved_jobs WHERE username = ? ORDER BY saved_at DESC',
                (username,)
            ).fetchall()

        saved_jobs = []
        for job in jobs:
            try:
                details = json.loads(job['job_details'])
                details['job_id'] = job['job_id']
                details['source'] = job['source']
                details['status'] = job['status']
                details['applied'] = job['applied']
                details['application_date'] = job['application_date']
                details['interview_date'] = job['interview_date']
                saved_jobs.append(details)
            except json.JSONDecodeError:
                # Handle dataset jobs referenced by index
                try:
                    idx = int(job['job_id'])
                    row = job_finder.df.loc[idx].to_dict()
                    row['job_id'] = str(idx)
                    row['source'] = job['source']
                    row['status'] = job['status']
                    row['applied'] = job['applied']
                    row['application_date'] = job['application_date']
                    row['interview_date'] = job['interview_date']
                    saved_jobs.append(row)
                except:
                    continue
        return saved_jobs
    except Exception as e:
        st.error(f"Error loading saved jobs: {str(e)}")
        return []
    finally:
        conn.close()

def delete_saved_job(username, job_id):
    """Remove a job from user's saved jobs"""
    conn = get_db_connection()
    try:
        conn.execute(
            'DELETE FROM saved_jobs WHERE username = ? AND job_id = ?',
            (username, job_id)
        )
        conn.commit()
        return True
    except Exception as e:
        st.error(f"Error deleting job: {str(e)}")
        return False
    finally:
        conn.close()

def analyze_skill_gaps(username, job_skills):
    """Analyze skill gaps between user and job requirements"""
    conn = get_db_connection()
    try:
        user = conn.execute('SELECT skills FROM users WHERE username = ?', (username,)).fetchone()
        if not user or not user['skills']:
            return None

        user_skills = set([skill.strip().lower() for skill in user['skills'].split(',')])
        required_skills = set([skill.strip().lower() for skill in job_skills.split(',')])

        missing_skills = required_skills - user_skills

        if missing_skills:
            # Get learning resources for missing skills
            resources = []
            for skill in missing_skills:
                resources.extend(learning_resources.get_resources(skill))

            # Store analysis
            conn.execute(
                'INSERT INTO skill_gaps (username, missing_skills, recommended_resources) VALUES (?, ?, ?)',
                (username, ', '.join(missing_skills), json.dumps(resources))
            )
            conn.commit()

            return {
                'missing_skills': list(missing_skills),
                'resources': resources
            }
        return None
    except Exception as e:
        st.error(f"Error analyzing skill gaps: {str(e)}")
        return None
    finally:
        conn.close()

# ====================== NETWORKING FUNCTIONS ======================
def send_connection_request(user_from, user_to):
    """Send a connection request to another user"""
    conn = get_db_connection()
    try:
        conn.execute(
            'INSERT OR IGNORE INTO connections (user_from, user_to, status) VALUES (?, ?, ?)',
            (user_from, user_to, 'pending')
        )
        conn.commit()
        return True
    except Exception as e:
        st.error(f"Error sending connection request: {str(e)}")
        return False
    finally:
        conn.close()

def get_connection_requests(username):
    """Get pending connection requests for a user"""
    conn = get_db_connection()
    try:
        requests = conn.execute(
            'SELECT user_from FROM connections WHERE user_to = ? AND status = ?',
            (username, 'pending')
        ).fetchall()
        return [req['user_from'] for req in requests]
    except Exception as e:
        st.error(f"Error getting connection requests: {str(e)}")
        return []
    finally:
        conn.close()

def accept_connection_request(user_from, user_to):
    """Accept a connection request"""
    conn = get_db_connection()
    try:
        conn.execute(
            'UPDATE connections SET status = ? WHERE user_from = ? AND user_to = ?',
            ('accepted', user_from, user_to)
        )
        conn.commit()
        return True
    except Exception as e:
        st.error(f"Error accepting connection: {str(e)}")
        return False
    finally:
        conn.close()

def get_connections(username):
    """Get all connections for a user"""
    conn = get_db_connection()
    try:
        # Get users who this user has connected with
        connections = conn.execute(
            '''SELECT user_to as username FROM connections WHERE user_from = ? AND status = ?
               UNION
               SELECT user_from as username FROM connections WHERE user_to = ? AND status = ?''',
            (username, 'accepted', username, 'accepted')
        ).fetchall()
        return [conn['username'] for conn in connections]
    except Exception as e:
        st.error(f"Error getting connections: {str(e)}")
        return []
    finally:
        conn.close()

# ====================== ENHANCED UI COMPONENTS ======================
def show_enhanced_home_page():
    """Display the enhanced home page"""
    st.markdown("""
    <div style="text-align: center; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 30px; border-radius: 10px; margin-bottom: 30px;">
        <h1 style="color: white; margin-bottom: 10px;">TechSphere Professional+</h1>
        <p style="color: white; font-size: 18px;">Your AI-Powered Career Intelligence Platform</p>
    </div>
    """, unsafe_allow_html=True)

    # Header image
    try:
        st.image("https://img.freepik.com/free-vector/business-team-putting-together-jigsaw-puzzle-isolated-flat-vector-illustration-cartoon-partners-working-connection-teamwork-partnership-cooperation-concept_74855-9814.jpg",
                use_container_width=True)
    except:
        st.image("https://via.placeholder.com/800x300?text=TechSphere+Professional+", use_container_width=True)

    # Feature cards with icons
    cols = st.columns(3)
    features = [
        ("🚀", "AI Job Matching", "Intelligent recommendations based on your skills"),
        ("📊", "Career Analytics", "Real-time market insights and salary data"),
        ("🤝", "Professional Network", "Connect with other professionals in your field"),
        ("📚", "Skill Development", "Personalized learning resources for skill gaps"),
        ("🔔", "Smart Alerts", "Instant notifications for perfect opportunities"),
        ("💼", "Application Tracking", "Manage your job applications and interviews")
    ]

    for i in range(0, 6, 3):
        with cols[0]:
            st.markdown(f"""
            <div style="background-color: #2D2D2D; padding: 20px; border-radius: 10px; margin-bottom: 15px; height: 150px;">
                <h3>{features[i][0]} {features[i][1]}</h3>
                <p>{features[i][2]}</p>
            </div>
            """, unsafe_allow_html=True)
        with cols[1]:
            st.markdown(f"""
            <div style="background-color: #2D2D2D; padding: 20px; border-radius: 10px; margin-bottom: 15px; height: 150px;">
                <h3>{features[i+1][0]} {features[i+1][1]}</h3>
                <p>{features[i+1][2]}</p>
            </div>
            """, unsafe_allow_html=True)
        with cols[2]:
            st.markdown(f"""
            <div style="background-color: #2D2D2D; padding: 20px; border-radius: 10px; margin-bottom: 15px; height: 150px;">
                <h3>{features[i+2][0]} {features[i+2][1]}</h3>
                <p>{features[i+2][2]}</p>
            </div>
            """, unsafe_allow_html=True)

    # Quick stats
    if not job_finder.df.empty:
        st.markdown("---")
        st.subheader("Market Insights at a Glance")
        stat_cols = st.columns(4)

        total_jobs = len(job_finder.df)
        unique_companies = job_finder.df['Company'].nunique()
        avg_salary = job_finder.df['Min Salary'].mean() if 'Min Salary' in job_finder.df.columns else "N/A"
        top_skill = job_finder.get_skill_demand().index[0] if not job_finder.get_skill_demand().empty else "N/A"

        stat_cols[0].metric("Total Jobs", f"{total_jobs:,}")
        stat_cols[1].metric("Companies", unique_companies)
        stat_cols[2].metric("Avg Salary", f"${avg_salary:,.0f}" if isinstance(avg_salary, (int, float)) else avg_salary)
        stat_cols[3].metric("Top Skill", top_skill)

def show_ai_recommendations_page(username):
    """Display AI-powered job recommendations"""
    st.subheader("🤖 AI-Powered Job Recommendations")

    conn = get_db_connection()
    try:
        user = conn.execute('SELECT skills FROM users WHERE username = ?', (username,)).fetchone()
        user_skills = user['skills'].split(',') if user and user['skills'] else []
    finally:
        conn.close()

    if not user_skills:
        st.warning("Please update your skills in your profile to get personalized recommendations")
        return

    with st.spinner("Analyzing your skills and finding the best matches..."):
        recommended_jobs = job_finder.recommend_jobs(user_skills, top_n=10)

        if recommended_jobs is not None and not recommended_jobs.empty:
            st.success(f"Found {len(recommended_jobs)} jobs that match your skills!")

            for idx, row in recommended_jobs.iterrows():
                match_percent = row['Match Score'] * 100

                with st.container():
                    st.markdown(f"""
                    <div style="background-color: #2D2D2D; padding: 15px; border-radius: 8px; margin-bottom: 15px; border-left: 4px solid #4CAF50;">
                        <h4>{row['Job Title']}</h4>
                        <p><strong>{row['Company']}</strong> • {row['Location']}</p>
                        <p>Required Skills: {row['Required Skills']}</p>
                        <div style="display: flex; justify-content: space-between; align-items: center;">
                            <div style="flex: 1;">
                                <div style="background-color: #3D3D3D; border-radius: 5px; padding: 3px;">
                                    <div style="background-color: #4CAF50; width: {match_percent}%; height: 20px; border-radius: 3px; text-align: center; color: white; font-weight: bold;">
                                        {match_percent:.1f}% Match
                                    </div>
                                </div>
                            </div>
                            <div style="margin-left: 15px;">
                                <button style="background-color: #2196F3; color: white; border: none; padding: 8px 15px; border-radius: 4px; cursor: pointer;">Save</button>
                            </div>
                        </div>
                    </div>
                    """, unsafe_allow_html=True)

                    # Save job button
                    if st.button(f"Save Job {idx}", key=f"save_rec_{idx}"):
                        if save_job(username, str(idx), row.to_dict(), "recommendation"):
                            st.success("Job saved to your profile!")
                            st.rerun()
        else:
            st.warning("No recommendations found. Try adding more skills to your profile.")

def show_network_page(username):
    """Display networking page"""
    st.subheader("🤝 Professional Network")

    tab1, tab2, tab3 = st.tabs(["My Connections", "Connection Requests", "Find Professionals"])

    with tab1:
        st.write("Your Professional Connections")
        connections = get_connections(username)

        if connections:
            for connection in connections:
                col1, col2 = st.columns([3, 1])
                with col1:
                    st.write(f"**{connection}**")
                with col2:
                    if st.button("Message", key=f"msg_{connection}"):
                        st.info(f"Messaging feature coming soon for {connection}")
        else:
            st.info("You don't have any connections yet. Send connection requests to build your network.")

    with tab2:
        st.write("Pending Connection Requests")
        requests = get_connection_requests(username)

        if requests:
            for req in requests:
                col1, col2, col3 = st.columns([3, 1, 1])
                with col1:
                    st.write(f"**{req}** wants to connect with you")
                with col2:
                    if st.button("Accept", key=f"acc_{req}"):
                        if accept_connection_request(req, username):
                            st.success(f"Connected with {req}")
                            st.rerun()
                with col3:
                    if st.button("Ignore", key=f"ign_{req}"):
                        st.warning("Ignore feature coming soon")
        else:
            st.info("No pending connection requests")

    with tab3:
        st.write("Find Professionals to Connect With")
        # This would typically search through users based on skills, industry, etc.
        st.info("Professional search feature coming soon")

        # Example suggested connections
        suggested_connections = ["data_scientist_23", "python_dev_45", "ml_engineer_99"]
        for suggested in suggested_connections:
            if suggested != username and suggested not in get_connections(username):
                col1, col2 = st.columns([3, 1])
                with col1:
                    st.write(f"**{suggested}** - Python, Machine Learning, Data Analysis")
                with col2:
                    if st.button("Connect", key=f"con_{suggested}"):
                        if send_connection_request(username, suggested):
                            st.success(f"Connection request sent to {suggested}")

def show_skill_development_page(username):
    """Display skill development and learning resources"""
    st.subheader("📚 Skill Development Center")

    conn = get_db_connection()
    try:
        user = conn.execute('SELECT skills FROM users WHERE username = ?', (username,)).fetchone()
        user_skills = user['skills'].split(',') if user and user['skills'] else []
    finally:
        conn.close()

    if user_skills:
        st.write("Your current skills:", ", ".join(user_skills))

        # Skill gap analysis for saved jobs
        saved_jobs = get_saved_jobs(username)
        if saved_jobs:
            st.subheader("Skill Gap Analysis")

            for job in saved_jobs[:3]:  # Analyze first 3 saved jobs
                if 'Required Skills' in job:
                    analysis = analyze_skill_gaps(username, job['Required Skills'])
                    if analysis:
                        with st.expander(f"Skill gaps for {job.get('Job Title', job.get('job_title', 'Unknown'))}"):
                            st.write("**Missing skills:**", ", ".join(analysis['missing_skills']))

                            st.write("**Recommended learning resources:**")
                            for resource in analysis['resources'][:3]:  # Show top 3 resources
                                st.markdown(f"- [{resource['name']} on {resource['platform']}]({resource['url']})")
        else:
            st.info("Save some jobs to see skill gap analysis")
    else:
        st.warning("Please add your skills to your profile to get personalized learning recommendations")

    # General learning resources by category
    st.subheader("Learning Resources by Category")

    categories = ["Python Programming", "Machine Learning", "Data Analysis", "Web Development"]
    selected_category = st.selectbox("Select a category", categories)

    if selected_category:
        resources = learning_resources.get_resources(selected_category)
        if resources:
            for resource in resources:
                st.markdown(f"""
                <div style="background-color: #2D2D2D; padding: 15px; border-radius: 8px; margin-bottom: 10px;">
                    <h4>{resource['name']}</h4>
                    <p><strong>Platform:</strong> {resource['platform']}</p>
                    <a href="{resource['url']}" target="_blank" style="color: #4CAF50; text-decoration: none;">➡️ Start Learning</a>
                </div>
                """, unsafe_allow_html=True)
        else:
            st.info("No resources found for this category")

def show_application_tracker_page(username):
    """Display job application tracking dashboard"""
    st.subheader("💼 Application Tracker")

    # Get saved jobs with different statuses
    saved_jobs = get_saved_jobs(username)
    applied_jobs = [job for job in saved_jobs if job.get('applied', 0) == 1]
    interview_jobs = [job for job in saved_jobs if job.get('status', '').lower() == 'interview']

    # Stats cards
    col1, col2, col3 = st.columns(3)
    col1.metric("Saved Jobs", len(saved_jobs))
    col2.metric("Applications", len(applied_jobs))
    col3.metric("Interviews", len(interview_jobs))

    # Application timeline
    if applied_jobs:
        st.subheader("Application Timeline")

        # Create timeline data
        timeline_data = []
        for job in applied_jobs:
            if job.get('application_date'):
                timeline_data.append({
                    'date': job['application_date'],
                    'title': job.get('Job Title', job.get('job_title', 'Unknown')),
                    'company': job.get('Company', job.get('employer_name', 'Unknown')),
                    'type': 'application'
                })
            if job.get('interview_date'):
                timeline_data.append({
                    'date': job['interview_date'],
                    'title': job.get('Job Title', job.get('job_title', 'Unknown')),
                    'company': job.get('Company', job.get('employer_name', 'Unknown')),
                    'type': 'interview'
                })

        # Sort by date
        timeline_data.sort(key=lambda x: x['date'])

        # Display timeline
        for event in timeline_data[-5:]:  # Show last 5 events
            icon = "📅" if event['type'] == 'application' else "🤝"
            st.write(f"{icon} **{event['date']}**: {event['title']} at {event['company']}")

    # Update job status
    st.subheader("Update Application Status")

    if saved_jobs:
        job_titles = [f"{job.get('Job Title', job.get('job_title', 'Unknown'))} - {job.get('Company', job.get('employer_name', 'Unknown'))}"
                     for job in saved_jobs]
        selected_job = st.selectbox("Select a job", job_titles)

        if selected_job:
            selected_index = job_titles.index(selected_job)
            job_id = saved_jobs[selected_index]['job_id']

            col1, col2 = st.columns(2)
            with col1:
                new_status = st.selectbox("Status", ["Saved", "Applied", "Interview", "Rejected", "Offer"])
            with col2:
                if new_status == "Applied":
                    application_date = st.date_input("Application Date")
                elif new_status == "Interview":
                    interview_date = st.date_input("Interview Date")
                else:
                    st.write("")  # Spacer

            if st.button("Update Status"):
                if new_status == "Applied":
                    update_job_status(username, job_id, new_status, application_date.strftime('%Y-%m-%d'))
                elif new_status == "Interview":
                    update_job_status(username, job_id, new_status, None, interview_date.strftime('%Y-%m-%d'))
                else:
                    update_job_status(username, job_id, new_status)

                st.success("Status updated successfully!")
                st.rerun()
    else:
        st.info("You haven't saved any jobs yet")

# ====================== MAIN APP ======================
def main():
    # Page configuration
    st.set_page_config(
        page_title="TechSphere Pro+",
        page_icon="🚀",
        layout="wide",
        initial_sidebar_state="expanded"
    )

    # Enhanced dark theme styling
    st.markdown("""
    <style>
        /* Main background */
        .stApp {
            background-color: #0E1117;
            color: #FAFAFA;
        }

        /* Text color */
        .stTextInput>label, .stSelectbox>label, .stTextArea>label,
        .stNumberInput>label, .stDateInput>label {
            color: #FAFAFA !important;
        }

        /* Header styling */
        .header {
            font-size: 2.5em;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            text-align: center;
            padding: 20px 0;
            margin-bottom: 25px;
            border-radius: 10px;
        }

        /* Cards */
        .feature-card {
            background-color: #1E1E1E;
            color: #FFFFFF;
            border-radius: 10px;
            padding: 20px;
            box-shadow: 0 4px 6px rgba(0,0,0,0.3);
            margin-bottom: 20px;
            border: 1px solid #333;
            transition: transform 0.2s;
        }

        .feature-card:hover {
            transform: translateY(-5px);
            box-shadow: 0 8px 15px rgba(0,0,0,0.4);
        }

        /* Job cards */
        .job-card {
            background-color: #1E1E1E;
            color: #FFFFFF;
            border-radius: 8px;
            padding: 15px;
            margin-bottom: 15px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.2);
            border-left: 4px solid #2196F3;
        }

        /* Notifications */
        .notification {
            background-color: #1A3A5F;
            color: #FFFFFF;
            padding: 12px;
            border-radius: 6px;
            margin: 8px 0;
            border-left: 4px solid #2196F3;
        }

        /* Buttons */
        .stButton>button {
            background-color: #4CAF50;
            color: white;
            border: none;
            padding: 10px 20px;
            border-radius: 5px;
            cursor: pointer;
            transition: background-color 0.3s;
        }

        .stButton>button:hover {
            background-color: #45a049;
        }

        /* Sidebar styling */
        .css-1d391kg {
            background-color: #0E1117;
        }

        /* Metric cards */
        .stMetric {
            background-color: #1E1E1E;
            padding: 15px;
            border-radius: 10px;
            border: 1px solid #333;
        }
    </style>
    """, unsafe_allow_html=True)

    # Initialize session state
    if 'logged_in' not in st.session_state:
        st.session_state.logged_in = False
        st.session_state.username = None

    # Navigation menu
    if st.session_state.logged_in:
        with st.sidebar:
            st.title("🚀 Navigation")

            # Main menu
            menu_options = [
                "Dashboard", "AI Job Recommendations", "Job Search",
                "Saved Jobs", "Application Tracker", "Skill Development",
                "Professional Network", "Profile", "Help"
            ]
            menu_choice = st.selectbox("Main Menu", menu_options)

            st.markdown("---")
            st.markdown(f"Welcome, **{st.session_state.username}**")

            # Quick actions
            st.markdown("### Quick Actions")
            if st.button("🔄 Check for New Opportunities"):
                check_job_alerts(st.session_state.username)
                st.success("Job alerts checked!")

            if st.button("📧 Email Saved Jobs"):
                saved_jobs = get_saved_jobs(st.session_state.username)
                if saved_jobs:
                    # This would typically email all saved jobs
                    st.info("Email feature coming soon")
                else:
                    st.warning("No saved jobs to email")

            if st.button("📊 Download Career Report"):
                st.info("Report generation coming soon")
    else:
        with st.sidebar:
            st.title("Navigation")
            menu_choice = st.selectbox(
                "Main Menu",
                ["Home", "Login", "SignUp"],
                key="main_menu"
            )

    # Page routing
    if menu_choice == "Home":
        show_enhanced_home_page()
    elif menu_choice == "Login" and not st.session_state.logged_in:
        show_login_page()
    elif menu_choice == "SignUp" and not st.session_state.logged_in:
        show_signup_page()
    elif st.session_state.logged_in:
        if menu_choice == "Dashboard":
            show_dashboard_page(st.session_state.username)
        elif menu_choice == "AI Job Recommendations":
            show_ai_recommendations_page(st.session_state.username)
        elif menu_choice == "Job Search":
            show_job_search_page(st.session_state.username)
        elif menu_choice == "Saved Jobs":
            show_saved_jobs_page(st.session_state.username)
        elif menu_choice == "Application Tracker":
            show_application_tracker_page(st.session_state.username)
        elif menu_choice == "Skill Development":
            show_skill_development_page(st.session_state.username)
        elif menu_choice == "Professional Network":
            show_network_page(st.session_state.username)
        elif menu_choice == "Profile":
            show_profile_page(st.session_state.username)
        elif menu_choice == "Help":
            show_help_page(st.session_state.username)
    else:
        st.warning("Please login to access this page")
        show_login_page()

if __name__ == '__main__':
    main()